name: Build and Push to Artifact Registry

on:
  push:
    branches: ["staging"]

jobs:
  build-push-image:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test-seeds
      PROJECT_ID: steady-force-423006-n3
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest asia-southeast1-docker.pkg.dev/$PROJECT_ID/seeds-test/$IMAGE_NAME:latest
        docker push asia-southeast1-docker.pkg.dev/$PROJECT_ID/seeds-test/$IMAGE_NAME:latest
